name: Trigger auto deployment for vscontainerapp1612

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/vscontainerapp1612-AutoDeployTrigger-ee699668-52d8-4db8-9df6-ee2198bbd07f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.VSCONTAINERAPP1612_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VSCONTAINERAPP1612_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VSCONTAINERAPP1612_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: crmqms5mxtggpcw.azurecr.io
          registryUsername: ${{ secrets.VSCONTAINERAPP1612_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VSCONTAINERAPP1612_REGISTRY_PASSWORD }}
          containerAppName: vscontainerapp1612
          resourceGroup: storagerg
          imageToBuild: crmqms5mxtggpcw.azurecr.io/vscontainerapp1612:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


